
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tfl_bikepoint_dbt'
version: '1.0.0'

config-version: 2

profile: 'tfl_bikepoint_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tfl_bikepoint_dbt:
    +materialized: view

    tfl_flatten:
      +materialized: table

    tfl_current:
      +materialized: view

    tfl_kpis:
      +materialized: view

    tfl_trend:
      +materialized: view